### ISSUE TITLE
Explicit Versioning - something that might (and probably will) replace Semantic Versioning

### ISSUE THREAD

**Issue by sapioit** [jlindsey/semantic#18]
I figured out that since you made a gem for semantic versioning, you might want to make one for something that is bound to replace the semantic versioning: the explicit versioning. Basicly, four words are enough to expalin it to most people: **_Release.Breaking.Feature.Fix**_

It removes the ambiguity of the field names, so instead of trying to guess what Major or Minor might reffer to in this case, you know what each field stands for. And you don't need to give pet/nick/code names to _cryptic version numbers_, instead, each release can have it's own number and pet/nick/code name, while also having the rest of the numbers reset to zero, unless you have something against it, in which case it should still work properly.

Here is a more in-depth article about it:  [**`Release.Breaking.Feature.Fix` or why the Semantic Versioning should be replaced with Explicit Versioning as soon as possible**](https://medium.com/p/92fc1f6bc73c)

**Comment by ant31** [comment]
@sapioit I don't see what is unclear with the semver: 
its documentation is clear. 
```
MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.
```
Regarding this I don't see much differences

**Comment by sapioit** [comment]
Because of marketing. You can't market Windows 10 as Windows 8.3 and expect people to not have misunderstandings. That's why after 8.1 (which was more of a service pack than a product in itself) they went to 10. And that's why you need a `GAMECHANGER` number, aside the `MAJOR`, `MINOR` and `PATCH`. Also, it rids you of that v3.2.6-9687 that we're likely to see, instead of v3.2.6.9687. People already started adapting that, but it is not mainstreamed, and the other users are either not informed or misinformed on what those numbers mean.
