### ISSUE TITLE
support `~>` style specification

### ISSUE THREAD

**Issue by axl411** [jlindsey/semantic#25]
I want to use `Semantic::Version#satisfies` to do this:

```ruby
Semantic::Version.new('1.6.8').satisfies('~> 1.5')
```

(see https://robots.thoughtbot.com/rubys-pessimistic-operator)

I expect this to return true but the lib now does not support this behavior. In `Semantic::Version#tilde_matches?` the logic makes it return false.

If it is OK, I'm happy to submit a PR to do this.

**Comment by jlindsey** [comment]
Thanks for the PR, I'll have a look a bit later today.
